#!/usr/bin/env bash

# Check if the number of arguments passed is less than 3
if [ "$#" -lt 4 ];
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
