#!/usr/bin/env bash

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Allow Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Set default page content
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

# Configure redirection
sudo tee /etc/nginx/sites-available/redirect.conf > /dev/null <<EOT
server {
    listen 80 default_server;
    location /redirect_me {
        return 301 https://www.youtube.com/;
    }
}
EOT

# Enable the redirection configuration
sudo ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configure 404 error handling
sudo sed -i '/^http {/a \    add_header X-Served-By "$HOSTNAME";' /etc/nginx/nginx.conf

# Restart Nginx service
sudo systemctl restart nginx
