#!/usr/bin/env bash
#configure Nginx server to listen to port 80

# Remove the default configuration file
rm /etc/nginx/sites-enabled/default
# Create a symbolic link to enable the default configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart the Nginx service
service nginx restart
