#!/usr/bin/env bash
#find out what’s keeping your Ubuntu container’s Nginx installation 
#from listening on port 80

# Remove the default configuration file
rm /etc/nginx/sites-available/default

# Create a symbolic link to enable the default configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service
service nginx restart
