#!/usr/bin/env bash
# Check if script is running inside Docker
if [ -f "/.dockerenv" ]; then
  HOSTS_FILE="/etc/hosts"
else
  HOSTS_FILE="/etc/hosts"
fi
echo "127.0.0.2 localhost" | sudo tee -a $HOSTS_FILE
echo "8.8.8.8 facebook.com" | sudo tee -a $HOSTS_FILE

echo "Configuration completed."
